### ISSUE TITLE
Building client side code

### ISSUE THREAD

**Issue by szymonlopaciuk** [olumidesan/scrabble#8]
Hi!

It's a great project! I forked it with the aim of making my native tongue version to play in these corona times. However, as I have no experience with React I can't seem to figure out how to build the client side code.

Just running `npm run build` leaves me with `build` in the wrong place (`/client/build` on `dev` vs `/app/client/build`/`/app/templates` on `master`), and when I move the files manually to the right ones it turns out that some paths are wrong inside of the files as well (`/...` instead of `/client/build/...`). Is there a vital step I am missing on how one should 'publish' the build, some script that magically puts everything in the right places?

Many thanks!

**Comment by olumidesan** [comment]
Hi, @szymonlopaciuk. Thanks for the comment!

No, there's no magic script unfortunately; there's a "hack" to it. Because of the project's structure, React's configuration needs to be modified to place the build files where Flask can serve them. There are also other modifications that's entirely my fault for not using an environment configuration file.

So, essentially, to get it to build in the right place, I do these things:
1. To get the build to have the `index.html` file in the `app/templates` directory, the webpack configuration needs to be modified in `client/node_modules/react-scripts/config/webpack.config.js`. 

![image](https://user-images.githubusercontent.com/37152066/104829485-558dca00-586c-11eb-826e-d97fd30ebfc4.png)
2. A similar maneuver has to be done in the `client/node_modules/react-scripts/config/path.js` to place the `client/build` directory correctly.

![image](https://user-images.githubusercontent.com/37152066/104829503-71916b80-586c-11eb-8430-b7224fbe737c.png)
3. In the `package.json` file, the `homepage` needs to be added.

![image](https://user-images.githubusercontent.com/37152066/104829522-a69dbe00-586c-11eb-810a-9a2eeac3514d.png)

4. Some hard-coded constants need to be uncommented to use the ones Jinja passes. This needs to be corrected in `client/src/helpers/axios.js` and `client/src/containers/User/user.jsx` 

![image](https://user-images.githubusercontent.com/37152066/104829540-d2b93f00-586c-11eb-977f-7ece5ce8e6c8.png)
![image](https://user-images.githubusercontent.com/37152066/104829541-d8af2000-586c-11eb-88b8-15a05b900931.png)

5. Token authentication needs to be enabled (so, only requests from valid game sessions work). In development, it's commented out, but in production, it needs to be uncommented. The `@token_auth.login_required` lines in `app/api/routes.py`

![image](https://user-images.githubusercontent.com/37152066/104829547-e795d280-586c-11eb-8537-48589c63d300.png)



I'm using screenshots, as I don't have any branch with this configuration. I know it's a hassle, but I'll fix it when I'm opportune. I hope this helps.

**Comment by szymonlopaciuk** [comment]
Thanks, that worked!
